export const GET_MOVIE_LIST: string = '@@FEATURES/MOVIE_LIST/GET_MOVIE_LIST';
export const FETCH_MOVIE_LIST: string = '@@FEATURES/MOVIE_LIST/FETCH_MOVIE_LIST';
export const SET_MOVIE_LIST_ERROR: string = '@@FEATURES/MOVIE_LIST/SET_MOVIE_LIST_ERROR';

export const GET_MOVIE: string = '@@FEATURES/MOVIE/GET_MOVIE';
export const FETCH_MOVIE: string = '@@FEATURES/MOVIE/FETCH_MOVIE';
export const SET_MOVIE_ERROR: string = '@@FEATURES/MOVIE/SET_MOVIE_ERROR';