export const MOVIE_LIST__GET = '@@FEATURES/MOVIE_LIST/MOVIE_LIST__GET';
export const MOVIE_LIST__FETCH = '@@FEATURES/MOVIE_LIST/MOVIE_LIST__FETCH';
export const MOVIE_LIST__FAIL = '@@FEATURES/MOVIE_LIST/MOVIE_LIST__FAIL';
